# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

# Dependabot configuration file
version: 2
updates:
  # Update npm dependencies in package.json
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"

  # Update Python dependencies managed by Poetry (pyproject.toml and poetry.lock)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
      
  # Update Docker dependencies in docker-compose.yml
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
      
